export class ScheduledAudit {
    auditCode:string;
    auditType:string;
    startDate:string;
    endDate:string;
    auditName:string;
    extDate:string;
    status:string;
    companyName:string;
    assetName:string;
    location:string;
    Quantity:string;
    remarks:string;
    schedule_audits_id:number;
    scheduleId:number;
    AvailableQty:string;
    newQty:number;
    diffqty:number;
    stack:string;
}