export class ScheduledAudit {
	roleId:number;
	status:string;
    manageAuditId:number;
	manageAuditNo:string;
	startDate:string;
	endDate:string;
	auditName:string;
	makerStatus:string;
	checkerStatus:string;
	companyStatus:string;
	auditType:string;
	auditorName:string;
	locationName:string;
	auditCompanyName:string;
	auditbranchName:string;
	loginedUser:string;
	scheduleAuditDetail:any;
}